"use strict";

// Product narrative stays separate from the record explorer and verified workflow calculations.
function storyLink(label,href){const link=element("a",label,"text-link");link.href=href;link.target="_blank";link.rel="noreferrer";return link;}
function findingCheck(title,copy,open=false){const item=element("details",undefined,"finding-check");item.open=open;item.append(element("summary",title),element("p",copy));return item;}
function chapterSummary(step,title){const summary=element("summary");summary.append(element("span",step,"chapter-number"),element("span",titleText(title)));return summary;}
function pageNext(label,view,copy){const next=element("section",undefined,"next-page");next.append(element("div","CONTINUE EXPLORING","eyebrow"),element("h2",label),element("p",copy),button(views[view][1]+" ↗",()=>navigate(view),"btn primary"));app.append(next);}
function storyRows(rows){const box=element("div",undefined,"story-rows");rows.forEach(([title,copy],i)=>{const row=element("section",undefined,"story-row");row.append(element("span",String(i+1).padStart(2,"0"),"story-number"),element("h3",title),element("p",copy));box.append(row);});return box;}
function workflowCards(){const cards=element("div",undefined,"workflow-grid");[
  ["VISUAL EXPLORATION","Start with the data.","Where should Vantara’s support team focus?","Compare six product areas, inspect priority and timing, open individual tickets, and follow the evidence to a review decision.","58 reporting incidents · 22 P1 cases","investigation","Open the visual workflow"],
  ["CONVERSATIONAL INVESTIGATION","Start with the question.","Should West copy East’s sales approach?","Follow a chain of management questions through volume, deal size, sales motion, and account mix before deciding what to do.","$43.715M gap · a different decision after follow-ups","case","Open the end-to-end case"]
].forEach(([label,title,question,copy,proof,view,cta])=>{const card=element("section",undefined,"workflow-card");card.append(element("span",label,"architecture-label"),element("h3",title),element("strong",question,"workflow-question"),element("p",copy),element("p",proof,"workflow-proof"),button(cta+" ↗",()=>navigate(view),"btn primary"));cards.append(card);});return cards;}

function openCollection(category){explore={category,query:"",facet:"",value:"",account:"",page:0};navigate("explore");}
function manualSourceSection(){
  const section=element("section",undefined,"home-section manual-source-section");section.dataset.purpose="manual-exploration";
  const intro=element("div",undefined,"manual-intro");intro.append(element("span","THE DATA WORKSPACE","architecture-label"),element("h2","Explore Without Asking the AI"),element("p","Browse accounts, filter opportunities, inspect support tickets, and open source records yourself. The public workspace contains seven searchable synthetic indexes."),button("Open the Data Workspace ↗",()=>navigate("explore"),"btn primary"));
  const collections=element("div",undefined,"source-gallery");Object.entries(categoryInfo).forEach(([key,info])=>{const item=button("",()=>openCollection(key),"source-tile");item.append(element("span",info.label,"source-name"),element("strong",number(summary.totals[key])),element("span","Browse ↗","source-action"));collections.append(item);});section.append(intro,collections);return section;
}
function productScene(){
  const section=element("section",undefined,"product-scene");section.dataset.purpose="product-preview";
  const top=element("div",undefined,"scene-top");top.append(element("span","INSIDE THE WORKSPACE","architecture-label"),element("span","Verified Synthetic Snapshot","scene-snapshot"));section.append(top);
  const shell=element("div",undefined,"scene-shell"),rail=element("aside",undefined,"scene-rail"),main=element("div",undefined,"scene-main");
  rail.append(element("strong","Business Analyst"),element("span","Workspace","scene-rail-label"));[["Accounts","accounts"],["Opportunities","opportunities"],["Support Tickets","tickets"],["Product Issues","issues"]].forEach(([label,key])=>rail.append(button(label,()=>openCollection(key),"scene-collection")));rail.append(element("p","Explore the records behind the answer."));
  const tabs=element("div",undefined,"scene-tabs");tabs.setAttribute("role","group");tabs.setAttribute("aria-label","Choose a workspace preview");const body=element("div",undefined,"scene-body"),buttons=[];
  const show=mode=>{buttons.forEach((item,i)=>{item.classList.toggle("active",i===mode);item.setAttribute("aria-pressed",String(i===mode));});body.replaceChildren();
    if(mode===0){
      body.append(element("div","VANTARA / SUPPORT / INCIDENTS","scene-breadcrumb"),element("h3","See where support demand is concentrated."));
      const stats=element("div",undefined,"scene-stats");[["269","Incident Records"],["58","Reporting Incidents"],["22","Reporting P1 Cases"]].forEach(([value,label])=>{const item=element("div");item.append(element("strong",value),element("span",label));stats.append(item);});body.append(stats);
      const table=element("table",undefined,"scene-table"),head=element("thead"),header=element("tr");["Product Area","Incidents","P1"].forEach(label=>header.append(element("th",label)));head.append(header);table.append(head);const rows=element("tbody");
      [["Revenue Analytics & Reporting",58,22],["Invoicing & Payment Lifecycle",53,21],["Billing & Subscription Management",47,16],["Checkout & Customer Experience",45,13],["Developer Experience & APIs",36,9],["Merchant Billing & Contracts",25,12]].forEach(([area,count,p1])=>{const row=element("tr"),name=element("td");name.append(button(area,()=>{explore={category:"tickets",query:"",facet:"ticket_type",value:"incident",facet2:"product_areas",value2:area,account:"ACC-013",page:0};navigate("explore");},"record-button"));row.append(name,element("td",String(count)),element("td",String(p1)));rows.append(row);});const unclassified=element("tr");unclassified.append(element("td","No Recorded Product Area"),element("td","5"),element("td","1"));rows.append(unclassified);table.append(rows);body.append(table,element("p","Account ACC-013 · All 269 incidents are marked solved. Counts do not establish current impact.","scene-note"),button("Follow the Visual Workflow ↗",()=>navigate("investigation"),"btn"));
    }else{
      body.append(element("div","EAST / WEST / ALL RECORDED OPPORTUNITIES","scene-breadcrumb"),element("h3","A better decision starts with the next question."));
      const prompt=element("blockquote","East leads on contract value. Should West copy its approach?","scene-prompt");body.append(prompt);
      const brief=element("div",undefined,"scene-brief");brief.append(element("span","DECISION BRIEF","architecture-label"),element("strong","Do not copy East’s playbook based on totals."),element("p","East’s recorded won ACV is $43.715M higher, but West has 1.7% more won ACV per indexed account. The account mixes differ, so the totals do not establish which team sells better."));
      const checks=element("ul");["Separate volume from average deal size.","Compare sales motion and account coverage.","Commission a matched pipeline review before a rollout."].forEach(copy=>checks.append(element("li",copy)));brief.append(checks);body.append(brief,element("p","Precomputed Case · ACV is annual contract value, not revenue or cash.","scene-note"),button("Read the Decision and Follow-Ups ↗",()=>navigate("case"),"btn primary"));
    }
  };
  ["Data Explorer","Analyst Brief"].forEach((label,index)=>{const item=button(label,()=>show(index),"scene-tab");buttons.push(item);tabs.append(item);});main.append(tabs,body);shell.append(rail,main);section.append(shell);show(0);return section;
}
function renderOverview(){
  app.replaceChildren();
  const hero=element("section",undefined,"hero home-hero");
  const left=heading("MODEL-AGNOSTIC · LOCAL-FIRST","Ask a business question. Follow the evidence.","A business analyst engine for leaders, analysts, and operations teams. It brings company data, business definitions, and analytical tools into one workspace, with a language model you can replace.");
  const actions=element("div",undefined,"actions");actions.append(button("Explore the Demo ↗",()=>navigate("workflows"),"btn primary"),button("Watch the analyst demos",()=>navigate("about")));left.append(actions,element("p","Interactive Portfolio Demo · Synthetic Data · No Live Model Call","demo-expectation"),element("p","Built by Julio Campos · Applied AI engineering, business analysis, and product design.","maker-line"));
  const aside=element("aside",undefined,"hero-aside");aside.append(element("div","A QUESTION WORTH INVESTIGATING","eyebrow"),element("strong","Should West copy East’s sales approach?"),element("p","East leads by $43.715M in recorded won ACV. West leads by 1.7% per indexed account. The follow-ups lead to a narrower decision: hold the rollout and review comparable pipeline."),button("See the end-to-end case ↗",()=>navigate("case"),"btn"));hero.append(left,aside);app.append(hero);
  app.append(productScene());
  const foundation=element("section",undefined,"home-section foundation-section");foundation.append(sectionHead("Business context. Exact analysis. Evidence you can inspect.","The model supplies language and reasoning. The engine supplies the definitions, tools, and source trail that make a business answer reviewable."));
  const pillars=element("div",undefined,"foundation-pillars");[["01","Connect the Context","Bring structured records and relevant documents together under shared business definitions."],["02","Do the Analytical Work","Use deterministic calculations, governed queries, and retrieval to investigate the question."],["03","Make the Answer Checkable","Trace material findings to sources, methods, assumptions, and the limits of the evidence."]].forEach(([num,title,copy])=>{const item=element("section");item.append(element("span",num,"pillar-number"),element("h3",title),element("p",copy));pillars.append(item);});foundation.append(pillars,button("See How It Works ↗",()=>navigate("how"),"text-button"));app.append(foundation);
  const workflows=element("section",undefined,"home-section workflow-section");workflows.dataset.purpose="workflow-comparison";workflows.append(sectionHead("Two Ways to Investigate","Start with the data and choose your own path, or start with a business question and follow the analytical sequence."),workflowCards());app.append(workflows);
  app.append(manualSourceSection());
  const engineering=element("section",undefined,"home-section home-engineering");const engineeringCopy=element("div");engineeringCopy.append(element("span","APPLIED AI ENGINEERING","architecture-label"),element("h2","Follow the work all the way down."),element("p","Model serving, semantic catalogs, typed tools, agent orchestration, source replay, and evaluation. Inspect the design choices behind the interface and the boundaries still being qualified."),button("Explore the Engineering ↗",()=>navigate("engineering"),"btn"));const skills=element("div",undefined,"engineering-keywords");["Model Adapters","SQL + Python","Retrieval / RAG","Pydantic AI","Evidence Lineage","Evaluation Gates"].forEach(label=>skills.append(element("span",label)));engineering.append(engineeringCopy,skills);app.append(engineering);
  const status=element("details",undefined,"technical-notes home-status");status.append(element("summary","Project Status: What Is Built, Demonstrated, and Next"));const cards=element("div",undefined,"status-grid");[["BUILT LOCALLY","Local model integration, analytical tools, business semantics, provenance, and evaluation checks."],["SHOWN HERE","A working source explorer, two verified sample workflows, and four simulated videos using synthetic data."],["STILL TO QUALIFY","Reliable open-ended conversations, new-company transfer, and production deployment. Model development is paused."]].forEach(([label,copy])=>{const card=element("div",undefined,"status-card");card.append(element("span",label,"architecture-label"),element("p",copy));cards.append(card);});status.append(cards,element("p","The public demo runs in your browser without an LLM. Its workflows are precomputed, source-backed examples; the local engine is developed separately.","note"));app.append(status);
  pageNext("Why build an engine around a model?","why","The business problem is bigger than generating a fluent answer.");
}

function renderWhy(){
  app.replaceChildren(heading("WHY IT EXISTS","A good model needs a business foundation.","Company knowledge lives across systems. A useful analyst has to bring the right records, definitions, calculations, and evidence together before a recommendation is worth acting on."));
  app.append(sectionHead("Who It Is For","A shared workspace for the people framing the question, doing the analytical work, and building the system."));
  app.append(storyRows([["Business Leaders and Operators","Investigate a business concern, compare possible explanations, and decide what evidence is needed before acting."],["Analysts and Functional Teams","Work across sales, finance, support, and documents with shared definitions and traceable calculations."],["Data and AI Teams","Inspect the contracts, orchestration, model boundary, and evaluation approach behind the experience."]]));
  app.append(sectionHead("The business challenge","A leadership question rarely fits inside one report. Someone must connect the records, agree on what the measures mean, and decide whether the evidence is strong enough to act."));
  const why=element("div",undefined,"story-rows");
  [
    ["01","Connect the business picture","The sales story may be in CRM, delivery details in support records, and obligations in contracts. Reconciling those sources is part of the work before a business conclusion can be trusted."],
    ["02","Agree on what the numbers mean","“Revenue,” “bookings,” and “cash” describe different things. A useful comparison needs shared definitions, compatible periods, and the right population. The model needs those rules as much as it needs the records."],
    ["03","Make the conclusion possible to check","A useful answer should show the size of a change, what supports the explanation, and what is still unknown. Managers need a route from the recommendation back to the figures, assumptions, and sources."]
  ].forEach(([num,title,copy])=>{const row=element("section",undefined,"story-row");row.append(element("span",num,"story-number"),element("h3",title),element("p",copy));why.append(row);});app.append(why);


  app.append(sectionHead("What does the engine add?","The model contributes language understanding and reasoning. The application provides the operating context in which that reasoning can do useful work."));
  app.append(storyRows([["Approved access to the business","A CRM, finance system, contract repository, and support platform have different identities, permissions, and meanings. Connecting them requires more than placing files in a prompt."],["A repeatable way to investigate","The engine exposes analytical capabilities, verifies their inputs, records what ran, and checks the answer against the evidence. A hypothesis becomes a finding only when the available tools actually test it."],["Control over deployment","Some teams prefer sensitive records to remain inside their environment. Local or company-managed inference is a design option. An approved hosted model could be another option once its adapter and controls are validated."]]));
  const value=panel("Where the value would show up","Fewer manual handoffs between reports, less time reconciling conflicting definitions, and a shorter route from an executive question to a reviewed answer. These are intended benefits. A company pilot must measure them against its current process.");
  value.append(button("See the implementation and scorecard ↗",()=>navigate("roadmap")));app.append(value);
  pageNext("How the investigation works","how","Follow the responsibilities from a business question to a cited answer.");
}

function renderHow(){
  app.replaceChildren(heading("HOW IT WORKS","Language, tools, and evidence working together.","The user supplies the business concern. The intended engine identifies the relevant approved sources, chooses the analysis, checks the result, and explains what the evidence supports."));
  app.append(sectionHead("The end goal: ask, investigate, verify","A business analyst and internal strategy consultant that works across approved sources. The user supplies the business question; the system handles the investigation. This is the intended product experience."));
  const vision=element("div",undefined,"vision-flow");
  [
    ["01 / ASK","Start with the business problem","“Bookings rose, but revenue is flat. Why? Break it down by region and explain the biggest drivers.”"],
    ["02 / DISCOVER","Find approved evidence","Identify relevant CRM, finance, and document sources; respect scope, permissions, and business definitions."],
    ["03 / INVESTIGATE","Use the right tools","Retrieve passages, run validated SQL/Python calculations, reconcile sources, and test competing explanations."],
    ["04 / EXPLAIN","Return a decision-ready brief","Quantify the change, explain what supports it, identify uncertainty, and recommend next checks. Let the user inspect the what, why, and how."]
  ].forEach(([label,title,copy])=>{const card=element("div",undefined,"vision-step");card.append(element("span",label,"architecture-label"),element("h3",title),element("p",copy));vision.append(card);});app.append(vision);

  app.append(sectionHead("Connect your data and your meaning","A new company implementation starts with a scoped setup. It maps source identities and business definitions before questions are trusted."));
  app.append(storyRows([["Admit the sources","Connect approved exports or read-only reporting views from CRM, ERP, finance, support, and documents. Record permissions, coverage, refresh expectations, and the original source identities. Generic live connectors remain future work."],["Define the business","Map account and product IDs, joins, metric definitions, grain, currencies, and fiscal periods. Agree what “orders,” “bookings,” “revenue,” and “margin” mean, then reconcile known totals."],["Expose the tools","Make supported calculations, structured queries, and document retrieval available through typed contracts. Use SQL or Python for exact analysis and retrieval for relevant passages. RAG is one subsystem within the investigation."]]));
  app.append(sectionHead("Which part does the work?","Model reasoning and application controls have different jobs. A stronger model should improve interpretation without requiring new rules for every way a person might phrase a question."));
  const split=element("div",undefined,"split");split.append(panel("The model","Interprets business language, follows references across messages, proposes a plan, selects appropriate tools, tests ideas with their results, and explains the findings. General conversation and compound-request reliability are still qualification gaps."),panel("The application","Admits sources, checks scope and tool arguments, runs deterministic calculations, records evidence, enforces execution budgets, verifies citations, and preserves the investigation for review."));app.append(split);
  app.append(sectionHead("What the answer should contain","A concise management conclusion first, with deeper evidence available when the user needs it."));
  app.append(storyRows([["What was found","Verified facts, measurable differences, decisive contributors, and the business implication. Changes include their baseline, comparison, magnitude, and units."],["Why it supports the answer","Analytical findings, tested explanations, uncertainty, and the evidence supporting each material claim. Observation, inference, and causation remain distinct."],["How it was calculated","Executed tools, parameters, filters, source scope, assumptions, calculations, and citations. This explains the recorded analytical method rather than exposing private model reasoning."],["What to do next","A supported recommendation, the missing evidence needed to close a gap, and a human decision gate. Confidence reflects coverage and consistency rather than an invented probability."]]));
  const note=panel("One workspace, two entry points","A user can explore records and open a finding, or ask a question and inspect the evidence produced by an investigation. The visual workspace is working in this public demo. The conversational case illustrates the intended experience with verified, precomputed findings.");app.append(note);
  pageNext("Choose a sample workflow","workflows","See how the same evidence discipline supports two different ways of working.");
}

function renderWorkflows(){
  app.replaceChildren(heading("TWO SAMPLE WORKFLOWS","Start with records. Or start with a question.","The visual path gives the user control of the navigation. The conversational path lets the question drive the analytical sequence. Both end with inspectable evidence and a bounded decision."));
  app.append(workflowCards());
  app.append(sectionHead("What is functionally different?","These are two interfaces into the same intended analytical foundation."));
  const table=element("div",undefined,"comparison-matrix");
  [["Entry point","An account or a data collection","A management question"],["Who chooses the next step?","The user follows filters, breakdowns, and record links","The intended agent proposes and executes supported analytical steps"],["What you inspect","Counts, priorities, dates, and individual source records","Follow-up questions, competing readings, calculations, and a decision brief"],["The examples here","Vantara support: product areas to P1 tickets to a review plan","East/West sales: headline gap to volume, mix, and a rollout decision"],["What is actually running?","Browser filters, record inspection, and deterministic counts","A precomputed, annotated sequence; no live conversation or model call"]].forEach(([label,visual,conversation])=>{const row=element("section",undefined,"matrix-row");row.append(element("h3",label),element("p",visual),element("p",conversation));table.append(row);});const labels=element("div",undefined,"matrix-row matrix-head");labels.append(element("span","COMPARE THE PATHS","architecture-label"),element("strong","Visual exploration"),element("strong","Conversational investigation"));table.prepend(labels);app.append(table);
  const explorePanel=panel("Explore without asking the AI","The public workspace contains seven searchable source indexes: accounts, opportunities, support tickets, product issues, knowledge articles, internal documents, and call transcripts. Filter dimensions together, browse by account, and open the recorded fields.");
  explorePanel.append(button("Open the data workspace ↗",()=>navigate("explore"),"btn primary"));app.append(explorePanel);
  app.append(element("p","Both case pages retain their source scope, methods, missing evidence, proposed owner, decision criteria, and outcome checks. Operational interventions are proposed, not completed business actions.","note"));
  pageNext("Watch four investigations unfold","about","The videos illustrate support, contract comparison, sales performance, and product priorities.");
}

function renderEngineering(){
  app.replaceChildren(heading("ENGINEERING DEEP DIVE","The system behind the answer.","A modular local prototype spanning model serving, verified data, business semantics, agent orchestration, deterministic analytics, retrieval, evidence lineage, and evaluation. Later experimental components remain local; the linked public repository contains published milestones."));
  const contribution=element("section",undefined,"contribution-band");
  contribution.append(element("span","BUILT BY JULIO CAMPOS · FROM BUSINESS PROBLEM TO WORKING PROTOTYPE","architecture-label"),element("h2","The design choices behind the experience."),element("p","I translated the business need into a modular system: model serving, data engineering, semantic modeling, agent orchestration, evaluation, and a usable workspace. Language interpretation and tool selection belong with the model; exact calculations with code; source verification with an inspectable evidence layer."));
  const skills=element("div",undefined,"skill-strip");["Local inference","Typed tool contracts","SQL + Python analytics","Retrieval / RAG","Evidence lineage","Evaluation harness","Dashboard + UX"].forEach(label=>skills.append(element("span",titleText(label))));contribution.append(skills);

  app.append(element("p","Built by Julio Campos · Applied AI engineering, business analysis, and product design.","maker-line"));
  const principles=element("details",undefined,"technical-notes");principles.append(element("summary","Core Design Principles"));
  const choices=element("div",undefined,"story-rows");
  [["01","Control where analysis happens","Sensitive sales pipelines, customer histories, and commercial terms may need to stay inside a company’s environment. Local inference gives a deployment choice; production identity and access controls still require implementation."],["02","Keep the intelligence replaceable","Models improve faster than business definitions change. Separate the model adapter from analytical tools and evidence contracts so a new candidate can be tested against the same work. Portability still has to be demonstrated."],["03","Make useful answers testable","A fluent answer is only part of the result. Check the figures, scope, requested parts, and source references; retain attempts so failures can be traced to data, tools, orchestration, or the model."]].forEach(([num,title,copy])=>{const row=element("section",undefined,"story-row");row.append(element("span",num,"story-number"),element("h3",title),element("p",copy));choices.append(row);});principles.append(choices);
  const pipeline=element("ol",undefined,"system-pipeline");[["INTERFACE","Question + conversation"],["MODEL","Provider adapter"],["EXECUTION","Governed tools"],["EVIDENCE","Ledger + source replay"],["REVIEW","Answer + audit"]].forEach(([label,copy])=>{const item=element("li");item.append(element("span",label,"architecture-label"),element("strong",copy));pipeline.append(item);});app.append(pipeline);
  const componentCatalog=element("details",undefined,"technical-notes component-catalog");componentCatalog.append(element("summary","Component Catalog and Technical Notes"));
  componentCatalog.append(sectionHead("Under the hood","Working components, explicit boundaries and repeatable checks. This is where the portfolio demonstrates the engineering behind the interface."));
  const architecture=element("div",undefined,"architecture-grid");
  [
    ["01 / MODEL BOUNDARY","Keep the intelligence replaceable","Apple Silicon + MLX/MLX-VLM serves the current local model through an OpenAI-compatible API. Application contracts sit above the provider adapter; each replacement must pass transport and answer-quality checks."],
    ["02 / DATA ENGINEERING","Establish a source of truth","Pinned synthetic JSON, checksum verification, normalized SQLite, validated relationships, and read-only queries. Report parity checks compare the database with the reference source; original record IDs survive the transformation."],
    ["03 / BUSINESS SEMANTICS","Define what the numbers mean","A governed catalog defines entities, joins, metric definitions, grain, units, time coverage, and enabled methods. It distinguishes a missing input from an unavailable calculation or an unsupported inference."],
    ["04 / RETRIEVAL · RAG","Find evidence in the documents","Scoped lexical retrieval returns approved document passages with section, line range, and SHA-256 provenance. Retrieval is one tool within the investigation; structured questions can use analytical queries instead."],
    ["05 / AGENT ORCHESTRATION","Turn language into tool use","Native tool calling reaches typed Python reports and parameterized SQL. An experimental Pydantic AI loop handles model-led tool selection. Host-side validation, source scope, and execution budgets constrain what runs."],
    ["06 / PROVENANCE · EVALS","Make the result reproducible","Content-addressed evidence, claim-level citations, calculation replay, durable run records and versioned scenarios. Checks cover figures, sources, scope, and answer completeness, alongside speed and memory."]
  ].forEach(([label,title,copy])=>{const card=element("section",undefined,"architecture-card");card.append(element("span",label,"architecture-label"),element("h3",title),element("p",copy));architecture.append(card);});componentCatalog.append(architecture);
  const technical=element("details",undefined,"technical-notes");technical.append(element("summary","Inspect the technical design decisions"));
  const technicalBody=element("div",undefined,"technical-body");
  [
    ["Contracts beyond the prompt","Typed schemas and runtime validation check tool arguments and evidence references. Native structured output, tool calls and multi-turn continuation are tested at the actual serving boundary; a valid JSON shape alone cannot establish a correct business answer."],
    ["History that stays inspectable","Evidence retains source identity, method, arguments, results, and hashes. Event time and the time information became available are distinct. Saved attempts preserve their code and model identities so a later change cannot quietly rewrite an earlier result."],
    ["Evaluation that measures useful work","Versioned cases check requested parts, numerical correctness, citations, missing-data behavior, and inference limits. Deterministic replay checks the calculations independently. Resource measurements and focused regressions accompany model qualification; an official Enterprise-Bench score remains a future milestone."]
  ].forEach(([title,copy])=>technicalBody.append(panel(title,copy)));technical.append(technicalBody);componentCatalog.append(technical);

  app.append(sectionHead("Eight Engineering Boundaries","Explore each subsystem, the responsibilities it owns, and the integration still to qualify. The local model has passed selected checks; reliable general business conversations remain unqualified."));
  const chapters=element("div",undefined,"engineering-chapters");
  [
    ["01","Serving and provider transport","OpenAI-compatible Chat Completions HTTP keeps MLX-specific imports outside the application. The current Qwen3.8 vision-language baseline uses MLX-VLM over Apple Silicon; text-only serving still needs the correct native template. Application types and the provider adapter are separate. A future transport must preserve tool messages, continuation, structured-output behavior, and durable session identity.",
      "Qualification checks the actual accepted and rejected decoder outputs, native tool arguments, multi-turn tool continuation, context and output capacity, precision, runtime versions, latency, and memory. A process RSS sample is not a Metal peak-memory measurement. A compatible endpoint is the start of qualification, not evidence of interchangeable behavior."],
    ["02","Data admission and storage","The approved synthetic source is pinned by commit and manifest hashes. Original JSON remains the reference; a normalized SQLite repository provides read-only analytical access with relationship checks and parity verification. Source-specific adapters own field names and joins while reusable analytical functions operate on application types.",
      "Public browsing uses an explicit field allowlist. It excludes document bodies, people/contact fields, saved model attempts, and the separate finance test world. Live company refresh, change-data capture, and automated onboarding would need connector-specific coverage and integrity tests."],
    ["03","Semantic and capability catalogs","A governed catalog describes entities, joins, measures, grain, units, time coverage, source locators, method versions, input schemas, output shapes, and inference limits. Planning, dispatch, evidence construction, and evaluation refer to those definitions instead of maintaining separate copies in prompts.",
      "The catalog separates missing input from an unavailable calculation and from an unsupported inference. It also keeps annual contract value, recognized revenue, invoice value, cash, and order count distinct. Catalog identities allow a saved investigation to retain the definitions under which it was run."],
    ["04","Model-led orchestration","An experimental Pydantic AI loop lets the model interpret language and select typed tools, observe returned evidence, and continue or stop. The application controls source authority, scope, request limits, tool-call budgets, and run persistence. Original planning and controller paths remain preserved with their historical contracts.",
      "The desired conversation can include several requests in one message, corrections, and references such as “those shares.” Every requested part must remain accounted for, including blocked parts. A missing capability should identify the necessary calculation or source instead of silently answering a different question. This behavior remains an acceptance target."],
    ["05","Deterministic analysis and retrieval","Reviewed Python reports and governed parameterized SQL perform the numerical work. Financial scenarios distinguish signing dates, service periods, revenue events, contributor offsets, and contractual service-start grouping. Document tools use bounded lexical retrieval with passage-level source locations.",
      "Retrieval does not define the architecture. It supplies document evidence alongside structured reports. A future hybrid lexical/vector retriever or sandboxed code tool would require its own admission, permission, execution, and evaluation boundary. Neither is claimed as a working enterprise subsystem here."],
    ["06","Evidence, claims, and reproducibility","Content-addressed evidence records preserve the approved source, executed method, validated arguments, returned values, logical source locations, record IDs, and hashes. A citation must resolve to admitted evidence. Claim bindings retain dimensions, units, periods, and result paths; deterministic replay checks calculations against the authenticated source.",
      "Material recommendations should show their factual basis, analytical limits, and human review requirement. The answer explains the what, why, and how through recorded methods and evidence. A plausible narrative or a valid JSON shape cannot substitute for an executed analysis."],
    ["07","Time, state, and failure recovery","Event time and the time information became available are represented separately where the source supports them. Saved attempts retain original model output, execution state, code and model identities, and clean, degraded, insufficient, or failed outcomes. Historical schema readers and original attempts remain preserved.",
      "Invalid citations, conflicting evidence, failed execution, or stopped work stay visible. Request deadlines and budgets bound dispatch; a synchronous operation already running is not necessarily forcibly cancelled. Future distributed cancellation and recovery would need separate tests."],
    ["08","Evaluation and release decisions","Versioned cases check requested-part coverage, arithmetic, scope, units, source provenance, interpretation limits, and readable business conclusions. Deterministic checks run independently of the model; focused regressions identify the failing boundary before another live call. Qualification records latency, token counts, and the measured memory boundary.",
      "The candidate sequence starts with native transport, then retained answer-only cases, tool execution, and multi-turn conversation cases. A held-out company transfer test, human usefulness review, and an official Enterprise-Bench score remain future milestones. Known synthetic checks are not proof of enterprise generalization."]
  ].forEach(([num,title,copy,detail])=>{const chapter=element("details",undefined,"engineering-chapter");chapter.append(chapterSummary(num,title),element("p",copy),element("p",detail));chapters.append(chapter);});app.append(chapters,componentCatalog,principles,contribution);
  app.append(sectionHead("Reference points, not capability claims","Established platforms help benchmark the design principles. This project is an independently built proof of concept, not an implementation of these products."));
  const refs=element("div",undefined,"reference-row");
  [["Glean","Product, department, and industry navigation; company context and model choice.","https://www.glean.com/"],["Hex","Separate conversational analysis and data exploration, with a shared context layer.","https://hex.tech/"],["Palantir AIP","Data, tools, governance, observability, and evaluation around model execution.","https://www.palantir.com/docs/foundry/aip/overview"]].forEach(([name,copy,url])=>{const item=element("div");item.append(storyLink(name+" ↗",url),element("p",copy));refs.append(item);});app.append(refs);
  const designRefs=element("details",undefined,"technical-notes");designRefs.append(element("summary","Presentation Reference Points"));const designCopy=element("p");designCopy.append(storyLink("Ramp","https://ramp.com/")," informs the progression from business outcome to product demonstration. ",storyLink("Linear","https://linear.app/")," informs the space given to the interface and the separation of feature groups. ",storyLink("Retool","https://retool.com/")," provides a reference for explaining a technical platform through concrete business software. These are design references, not affiliations or capability claims.");designRefs.append(designCopy);app.append(designRefs);
  pageNext("How this could scale","scale","A larger model is one part of a larger operating system.");
}

const domainIdeas=[
  ["Revenue operations","Why is pipeline growing while revenue stays flat?","CRM, contract lines, revenue schedules, activation history, and account hierarchies.","Reconcile measures, segment the difference, identify contributors, and test timing explanations.","A reviewable account or segment plan, with missing evidence separated from a verified timing finding.","Contract value, cash, and recognized revenue need different measures."],
  ["Finance and FP&A","Revenue is stable. Why did gross margin move?","General ledger, recognized revenue, costs of service, products, cost centers, and allocation policies.","Build a margin bridge, separate mix from price and cost, and run explicit assumption scenarios.","A quantified explanation of the margin movement and a sensitivity range for a reviewed action.","The public sample has no matched costs. Forecasts need validated statistical methods and assumption disclosures."],
  ["Recruiting and people operations","Where is our hiring funnel slowing down?","ATS stage events, requisitions, interview scheduling, role requirements, and aggregated source data.","Compare time in stage, cohort conversion, vacancy age, and interview capacity for comparable roles.","A process bottleneck review and scheduling or sourcing experiment for human approval.","Start with aggregate process analysis. Individual hiring decisions need human judgment, appropriate access, and independently reviewed criteria."],
  ["Supply chain and operations","Why did on-time delivery fall while demand barely changed?","Purchase orders, inventory, shipment milestones, supplier lead times, demand, and capacity.","Segment delays, reconcile planned versus actual dates, and test supplier, stock, and capacity explanations.","A supplier or product review, followed by a controlled inventory or scheduling pilot where supported.","Forecasts and optimization need validated models, constraints, and uncertainty. Correlated delays do not establish a cause."],
  ["Customer support","Which issues deserve attention before the next customer review?","Ticket histories, severity, reopened cases, product issues, usage, and account context.","Compare demand, inspect repeated symptoms, verify issue links, and assess resolution quality.","A scoped quality review with traceable cases, an owner, and follow-up measures.","Ticket volume alone does not prove defects, customer loss, or financial impact."],
  ["Product and engineering","Which backlog items could relieve the most customer friction?","Issue state history, confirmed ticket links, usage, release events, and impact assessments.","Separate the active queue from historical volume, cluster verified symptoms, and compare candidate interventions.","An evidence-backed prioritization discussion and a measured release experiment.","Business impact and engineering effort must be supplied or estimated through reviewed methods."],
  ["Procurement and commercial terms","How do these agreements change our delivery obligations?","Executed agreements, amendments, service policies, supplier performance, and approved term definitions.","Retrieve cited clauses, compare obligations and exceptions, and reconcile terms with operational evidence.","A side-by-side negotiation brief with clear questions for the commercial or legal owner.","Templates are not executed contracts. Clause comparisons support review rather than legal conclusions."],
  ["Strategy and market planning","Which segments are worth a deeper expansion review?","Customer cohorts, market assumptions, product economics, pipeline history, and research sources.","Compare segment economics, separate scale from efficiency, and test scenarios using explicit assumptions.","A ranked set of research questions or pilot options with sensitivity and evidence coverage.","The engine should not invent market sizes, returns, or confidence probabilities."],
  ["Project and service delivery","Why are similar projects producing different outcomes?","Scope, milestones, capacity, timesheets, change orders, service costs, and client feedback.","Compare matched projects, quantify scope and cost differences, and test delivery explanations.","A process or staffing review with measurable pilot criteria.","Comparability, allocation rules, and source quality determine whether the comparison is useful."]
];

function renderPossibilities(){
  app.replaceChildren(heading("POSSIBILITIES","One investigation pattern. Many business domains.","The transferable idea is to connect a question with approved evidence, specialist tools, and a decision process. Each new domain needs its own definitions, data mappings, methods, and evaluation cases."));
  app.append(element("p","These are proposed applications. Recruiting, supply chain, forecasting, and the other extensions below are not connected capabilities in this public demo.","scope-banner"));
  const tabs=element("div",undefined,"domain-tabs");tabs.setAttribute("role","group");tabs.setAttribute("aria-label","Choose a business domain");
  const detail=element("section",undefined,"domain-detail");
  const showDomain=index=>{tabs.querySelectorAll("button").forEach((item,i)=>{item.classList.toggle("active",i===index);item.setAttribute("aria-pressed",String(i===index));});const [name,question,data,analysis,outcome,limit]=domainIdeas[index];detail.replaceChildren(element("span","POTENTIAL APPLICATION","architecture-label"),element("h2",name),element("blockquote",question));const rows=element("dl",undefined,"domain-description");[["Connected evidence",data],["Analytical work",analysis],["Useful output",outcome],["What must be validated",limit]].forEach(([label,copy])=>{const row=element("div");row.append(element("dt",label),element("dd",copy));rows.append(row);});detail.append(rows);};
  domainIdeas.forEach(([name],i)=>tabs.append(button(name,()=>showDomain(i),"domain-tab")));app.append(tabs,detail);showDomain(0);
  app.append(sectionHead("The domain changes. So does the industry context.","Reuse the shared engine; configure the business vocabulary, source relationships, and tested methods for the implementation."));
  app.append(storyRows([["Software and subscription businesses","Connect sales, subscriptions, activation, support, and product work to investigate expansion, service delivery, and commercial obligations."],["Manufacturing and distribution","Use parts, plants, suppliers, orders, inventory, and shipment milestones to explore shortages, delivery performance, capacity, and cost variation."],["Retail and consumer businesses","Compare SKU and store economics, promotions, fulfillment, and demand. Scenario work needs explicit assumptions and appropriate forecasting methods."],["Professional services","Investigate project margins, utilization, delivery milestones, scope changes, and client demand with consistent allocation rules."],["Financial services and healthcare operations","Start with approved operational questions such as service demand, procurement, staffing capacity, and process delays. Regulated or consequential decisions require specialized governance and human authority."]]));
  const reuse=panel("What stays reusable?","Provider adapters, tool contracts, execution controls, evidence identity, replay, conversation state, and evaluation machinery can remain shared. Company joins, definitions, permissions, domain methods, and expected answers must be configured and validated.");app.append(reuse);
  pageNext("From one Mac to an enterprise deployment","scale","See what changes when the data estate, model, and user population become much larger.");
}

function renderScale(){
  app.replaceChildren(heading("ENTERPRISE SCALE · PROPOSED ARCHITECTURE","More data. More compute. The same evidence discipline.","A private GPU server or approved hosted model could provide more reasoning capacity and throughput. Enterprise scale also requires stronger data access, execution, permissions, and operations around that model."));
  app.append(element("p","The Mac prototype is the starting point. The architecture below is a proposed expansion path, not a tested enterprise deployment or a capacity claim.","scope-banner"));
  app.append(sectionHead("Three deployment options","Choose where data and inference belong, then qualify the complete path."));
  const hosts=element("div",undefined,"portability-grid");[["LOCAL WORKSTATION","The starting point","Mac + MLX/MLX-VLM runs the current local baseline. Good for learning and scoped demonstrations; memory, latency, and concurrent use have practical limits."],["COMPANY-MANAGED GPU","A private runtime","A larger GPU host or cluster could serve a stronger model and queue concurrent investigations. Replace the serving adapter, then validate message formats, tools, quality, memory, and load."],["APPROVED HOSTED INFERENCE","A provider option","A company could choose a hosted model under its data and access policies. Minimize transmitted context, preserve source permissions and evidence contracts, and evaluate the adapter and answers."]].forEach(([label,title,copy])=>{const card=element("section",undefined,"architecture-card");card.append(element("span",label,"architecture-label"),element("h3",title),element("p",copy));hosts.append(card);});app.append(hosts);
  app.append(sectionHead("The model should receive the relevant evidence","Large enterprise tables belong in databases and analytical systems. Query and summarize them close to the source, then send bounded results and relevant document passages to the model."));
  const path=element("ol",undefined,"system-pipeline");[["SYSTEMS","CRM · ERP · documents"],["DATA ACCESS","Approved reporting views"],["SEMANTICS","Definitions + permissions"],["EXECUTION","Queries + retrieval"],["MODEL","Relevant evidence → answer"]].forEach(([label,copy])=>{const item=element("li");item.append(element("span",label,"architecture-label"),element("strong",copy));path.append(item);});app.append(path);
  const deep=element("div",undefined,"engineering-chapters");[
    ["01","Connect and maintain the data estate","Build versioned connectors for approved APIs, reporting views, warehouses, and document repositories. Use incremental refresh or change-data capture where appropriate. Map stable identities and relationships, retain provenance and freshness, and detect schema drift. Admission checks should reconcile known measures before the source becomes available to an analyst."],
    ["02","Execute analysis where it belongs","Push filtered joins and aggregations to the warehouse or lakehouse. Partition large queries, reuse validated reports, and cache results with their source version, semantics, and authorized scope. Run more specialized Python work in resource-limited workers with timeouts and isolated execution. Only relevant results enter the model context."],
    ["03","Retrieve documents with context and permissions","A future search layer could combine lexical retrieval, embeddings, metadata, and reranking. Document chunks need source locations and stable identities. Authorization must apply before evidence is returned, including caches and citations, so a user's answer never inherits another user's access."],
    ["04","Scale models and investigations independently","Separate model serving from orchestration and tool workers. Queues, admission control, batching, routing, and cancellation manage concurrent users and expensive work. Preserve per-run deadlines and tool budgets. A larger model may improve interpretation and multi-step reasoning; every candidate still needs the retained quality and conversation checks."],
    ["05","Make enterprise operations observable","Add identity, source-level permissions, secret handling, retention, monitoring, and recovery. Track source freshness, query time, model tokens, latency, cost per reviewed answer, failed steps, and citation coverage. Keep the executed methods and source versions available for replay rather than relying on a prose explanation alone."]
  ].forEach(([num,title,copy])=>{const chapter=element("details",undefined,"engineering-chapter");chapter.append(chapterSummary(num,title),element("p",copy));deep.append(chapter);});app.append(deep);
  app.append(sectionHead("What stronger compute could unlock","These are hypotheses to test against real workloads, not promised outcomes."));
  app.append(storyRows([["Deeper investigations","A more capable model could track compound questions, compare explanations, and use tools more reliably. It still needs sufficient source coverage and validated analytical methods."],["More simultaneous users","A larger serving pool and separate execution workers could support concurrent investigations. Measure queue delay, query contention, GPU memory, token throughput, and end-to-end answer quality under load."],["Richer source combinations","More connectors and a larger governed catalog could let one question cross more business systems. Correct joins, permissions, and time semantics become more important as coverage grows."]]));
  const capacity=panel("How to prove that it scales","Start with a representative question mix and real source distributions. Increase data volume and concurrency separately; measure p50/p95 response time, query cost, model memory, token use, citation correctness, and reviewer acceptance. Exercise stale sources, permission changes, timeouts, and recovery. No maximum data volume, concurrent-user count, or enterprise-grade SLA is claimed for this prototype.");app.append(capacity);
  const references=element("p",undefined,"note");references.append("Reference principles: ",storyLink("Hex’s warehouse and context model","https://hex.tech/"),", ",storyLink("Glean’s enterprise context and permissions","https://www.glean.com/"),", and ",storyLink("Palantir AIP’s governance and observability","https://www.palantir.com/docs/foundry/aip/overview"),". The expansion design above is our own proposed architecture.");app.append(references);
  pageNext("A practical implementation roadmap","roadmap","Expand through measured company pilots, model qualification, and demonstrated transfer.");
}

function renderRoadmap(){
  app.replaceChildren(heading("ROADMAP + IMPLEMENTATION","A foundation that can grow with the models.","Start with one recurring management question, prove a useful answer, and expand only when the data, tools, and evidence support the next capability."));
  app.append(sectionHead("The implementation case","Start with one recurring management question, an accountable business owner, and approved sources. Establish the current process, then test whether the engine produces a useful answer with less review effort."));
  const next=element("ol",undefined,"implementation-steps");
  [
    ["Qualify the next model","Test language interpretation, compound requests, tool use, and evidence-backed answers against the retained cases. Measure memory, speed, and completeness before expanding the live experience."],
    ["Connect a company’s data and meaning","Start with approved read-only sources or reporting views. Map customer and product IDs, define metrics and fiscal periods, reconcile totals, and check coverage. Live refresh and generic onboarding remain to be built."],
    ["Prove transfer, then pilot","Freeze the shared core and test a second approved dataset with independently checked answers. Record the setup effort. Then run a narrow, human-reviewed company pilot with explicit success criteria."],
    ["Prepare for operational use","Implement identity, permissions, secrets handling, retention, and monitoring for the chosen environment. Validate refresh, schema changes, and recovery. Extend domain tools only when their calculations and evidence pass review."]
  ].forEach(([title,copy],i)=>{const row=element("li");row.append(element("span",String(i+1).padStart(2,"0"),"story-number"));const body=element("div");body.append(element("h3",title),element("p",copy));row.append(body);next.append(row);});app.append(next);
  const pilot=element("section",undefined,"pilot-measures");pilot.append(element("span","PROPOSED PILOT SCORECARD · BENEFITS HAVE NOT BEEN MEASURED","architecture-label"),element("h3","Define success before expanding."));
  const measures=element("dl");
  [["Time to a reviewed answer","Compare elapsed time and reviewer effort with the existing process on the same questions."],["Answer quality","Check calculations, question coverage, and appropriate uncertainty against independently reviewed answers."],["Evidence coverage","Measure whether material claims resolve to the correct records and reproducible calculations."],["Implementation effort","Track data mapping and setup effort, then test transfer to a second company without rewriting the shared core."]].forEach(([label,copy])=>{const item=element("div");item.append(element("dt",label),element("dd",copy));measures.append(item);});pilot.append(measures,element("p","Agree targets and review criteria with the pilot owner before testing. No time savings, financial return, or production readiness is claimed by this preview.","note"));app.append(pilot);

  const portabilityHead=sectionHead("The opportunity ahead","Mac was the starting point because it was the hardware available to me. A reusable analyst engine could extend across models, deployment environments, and corporate functions as each is validated.");
  const portability=element("div",undefined,"portability-grid");
  [
    ["CHANGE THE MODEL","Keep the analytical foundation","Qualify a stronger local model, or add an approved hosted-provider adapter. Preserve business definitions, tools, and evidence contracts. Model-agnostic means replaceable with testing; compatibility is not automatic."],
    ["CHANGE THE HOST","Choose the deployment boundary","A company-managed server or other hardware is a future option. Replace the MLX serving layer, then validate dependencies, performance, and security. Linux/Windows packaging and private-cloud deployment have not been tested."],
    ["CHANGE THE FUNCTION","Reuse the investigation pattern","Revenue operations, finance, support, product, and contract analysis can share the pattern. Each needs its own approved data, semantic mappings, analytical tools, and evaluation cases. Forecasting would also need validated statistical methods."]
  ].forEach(([label,title,copy])=>{const card=element("section",undefined,"architecture-card");card.append(element("span",label,"architecture-label"),element("h3",title),element("p",copy));portability.append(card);});

  app.append(portabilityHead,portability);
  const tuning=element("details",undefined,"technical-notes tuning-note");tuning.append(element("summary","Where fine-tuning could fit"),element("p","After selecting and qualifying a baseline, fine-tuning could improve question interpretation, tool selection, or answer style using separately permitted training examples. Retrieval and source connections supply current business facts. Held-out evaluations must show a benefit over the untuned baseline; Enterprise-Bench evaluation data must stay out of training. No fine-tuned model is claimed here."));app.append(tuning);
  const qualification=element("div",undefined,"qualification-note");qualification.append(element("span","CURRENT CHECKPOINT","architecture-label"),element("strong","A working foundation, with a clear qualification gap."),element("p","The local 27B baseline has passed selected tool and evidence tests. Reliable general business conversations have not been qualified, and model experimentation is paused. A stronger model or larger machine may help; neither guarantees the missing behavior. The public demo remains a synthetic, read-only preview, with consequential conclusions subject to human review."));app.append(qualification);

  app.append(sectionHead("Where we can go from here","Separate useful product work from model-dependent qualification."));
  app.append(storyRows([["While model development is paused","Improve source exploration, reviewed-workflow presentation, evidence navigation, accessibility, and documentation. Preserve test cases, failed attempts, and the model-qualification package."],["When a candidate is worth testing","Qualify native transport and known answer cases first. Then test tool execution, follow-ups, corrections, compound requests, and missing evidence. Review the business usefulness of the result before connecting live asking."],["After a useful company pilot","Test a second company with the shared core frozen and independent expected answers. Build refresh, production permissions, and recovery for the selected environment. Forecasting, optimization, and new domains each need reviewed methods."],["For broader credibility","Pursue the official Enterprise-Bench protocol when ready. Keep published benchmark results separate from known synthetic checks, private experiments, and company-transfer evidence."]]));
  const closing=panel("Why this is a portfolio project","The work connects business problem framing with data engineering, local inference, agent design, deterministic analysis, provenance, evaluation, and product UX. The strongest demonstration is a useful answer whose figures and limitations remain inspectable.");
  closing.append(storyLink("Explore the published engine milestones ↗","https://github.com/gravelgaucho/ai-business-operations-analyst"));app.append(closing);
  pageNext("Return to the two workflows","workflows","See the business experience that these engineering choices are intended to support.");
}

function appendDataCoverage(){
  const coverage=element("details",undefined,"technical-notes data-coverage");coverage.append(element("summary","What is connected? Seven synthetic source indexes"));
  const content=element("div");
  const metrics=element("div",undefined,"metric-grid");
  [["accounts","Accounts"],["opportunities","Opportunities"],["tickets","Support tickets"],["issues","Product issues"]].forEach(([key,label])=>{const card=element("div",undefined,"metric-card");card.append(element("span",label),element("strong",number(summary.totals[key])),element("small","Verified synthetic source index"));metrics.append(card);});content.append(metrics);
  const categories=element("div",undefined,"category-grid overview-collections");
  Object.entries(categoryInfo).forEach(([key,info])=>{const card=button("",()=>{explore={category:key,query:"",facet:"",value:"",account:"",page:0};navigate("explore");},"category-card");card.append(element("span",number(summary.totals[key]),"count"),element("span",info.label,"label"),element("span","Open collection ↗","arrow"));categories.append(card);});content.append(categories);
  content.append(element("p","This public snapshot omits document bodies, contact details, saved model runs, and the separate finance test data. Source coverage is broader than the analyst’s qualified analytical capabilities.","note"));

  coverage.append(content);app.append(coverage);
}
